[package]
name = "stripng"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
iowrap = "0.2"
tempfile = "3"

[dependencies.failure]
default-features = false
features = ["std"]
version = "0.1"
